

// USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

// PARSERs
export const GET_PARSER_LIST = 'GET_PARSER_LIST'
export const PARSER_DETAIL = 'PARSER_DETAIL'
export const ADD_PARSER_LIST = 'ADD_PARSER_LIST'
export const REQUEST_PARSER_LIST = 'REQUEST_PARSER_LIST'
export const GET_PARSER_LIST_FAILURE = 'GET_PARSER_LIST_FAILURE'
export const SUCCESS_ADD_PARSER = 'SUCCESS_ADD_PARSER'

//parser
export const GET_PARSER = 'GET_PARSER'

// documents
export const DOCUMENT_LIST = 'PARSER_LIST'
export const DOCUMEN_DETAIL = 'PARSER_DETAIL'
export const ADD_DOCUMENT = 'ADD_DOCUMENT'
export const REQUEST_DOCUMENT_LIST = 'REQUEST_PARSER_LIST'
export const GET_DOCUMENT_LIST_FAILURE = 'GET_PARSER_LIST_FAILURE'

//document
export const GET_DOCUMENT = 'GET_DOCUMENT'
export const EXTRACT_DOCUMENT = 'EXTRACT_DOCUMENT'

// MSG
export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
