

// USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

// PARSERS
export const GET_PARSER_LIST = 'GET_PARSER_LIST'
export const PARSER_DETAIL = 'PARSER_DETAIL'
export const ADD_PARSER_LIST = 'ADD_PARSER_LIST'
export const REQUEST_PARSER_LIST = 'REQUEST_PARSER_LIST'
export const GET_PARSER_LIST_FAILURE = 'GET_PARSER_LIST_FAILURE'
export const SUCCESS_ADD_PARSER = 'SUCCESS_ADD_PARSER'
export const DELETE_PARSER = 'DELETE_PARSER'

//parser
export const GET_PARSER = 'GET_PARSER'
export const ADD_PARSER = 'ADD_PARSER'
export const UPDATE_PARSER = 'UPDATE_PARSER'

//parserRule
export const GET_PARSER_RULE = 'GET_PARSER_RULE'
export const ADD_PARSER_RULE = 'ADD_PARSER_RULE'
export const UPDATE_PARSER_RULE = 'UPDATE_PARSER_RULE'
export const DELETE_PARSER_RULE = 'DELETE_PARSER_RULE'

// documents
export const GET_DOCUMENT_LIST = 'GET_DOCUMENT_LIST'
export const ADD_DOCUMENT = 'ADD_DOCUMENT'
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'
export const REQUEST_DOCUMENT_LIST = 'REQUEST_DOCUMENT_LIST'
export const GET_DOCUMENT_LIST_FAILURE = 'GET_DOCUMENT_LIST_FAILURE'

//document
export const GET_DOCUMENT = 'GET_DOCUMENT'
export const EXTRACT_DOCUMENT = 'EXTRACT_DOCUMENT'
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT'

// MSG
export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
